name: Fetch NIFTY PE Data Daily

on:
  schedule:
    - cron: '0 7 * * *'  # Every day at 4 AM UTC
  workflow_dispatch:     # Allows manual runs

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run script
        run: python daily_nifty_pe_job.py

      - name: Commit updated CSV
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add nifty_pe_pb_div.csv
          git commit -m "📈 Daily update - $(date '+%Y-%m-%d')" || echo "No changes to commit"
          git push
