name: Fetch Daily Bulk Deals

on:
  schedule:
    - cron: '0 14 * * 1-5'   # Runs at 14:00 UTC (7:30 PM IST), Monday to Friday
  workflow_dispatch:         # Allows manual trigger from GitHub UI

permissions:
  contents: write            # Needed to push changes

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas numpy requests requests_html

      - name: Run script
        run: python daily_bulk_deals_update_job.py

      - name: Commit updated CSV
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add bulk.csv
          git commit -m "📈 Daily Bulk deals update - $(date '+%Y-%m-%d')" || echo "No changes to commit"

      - name: Push changes to repo
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
          git push origin main
